import type { Peptide } from './types';

// Stub peptide list — replace with full data as needed.
export const peptides: Peptide[] = [
  {
    id: 'bpc-157',
    name: 'BPC-157',
    aliases: ['Body Protection Compound 157'],
    categories: ['healing'],
    description: 'A synthetic peptide derived from a protective protein found in the stomach.',
    mechanism: 'Promotes angiogenesis, upregulates growth factors, and accelerates tissue repair.',
    primaryBenefits: ['Accelerated wound healing', 'Tendon & ligament repair', 'Gut healing', 'Anti-inflammatory'],
    sideEffects: ['Generally well tolerated', 'Mild nausea (rare)', 'Dizziness (rare)'],
    dosing: {
      typical: '250–500 mcg',
      range: '200–600 mcg',
      frequency: 'Once or twice daily',
      route: ['subcutaneous', 'intramuscular', 'oral'],
      cycleLength: '4–12 weeks',
      breakLength: '4 weeks',
      timing: 'Morning and/or pre-workout',
    },
    goals: ['healing', 'joints-pain', 'gut-health'],
    stacks: { synergistic: [], redundant: [], complementary: [] },
    halfLife: '~4 hours',
    storage: 'Refrigerate lyophilized powder; use within 30 days after reconstitution.',
    reconstitution: 'Reconstitute with bacteriostatic water.',
    experienceLevel: 'beginner',
  },
  {
    id: 'tb-500',
    name: 'TB-500',
    aliases: ['Thymosin Beta-4'],
    categories: ['healing'],
    description: 'A synthetic version of Thymosin Beta-4, promotes healing and reduces inflammation.',
    mechanism: 'Upregulates actin polymerization and promotes cell migration and proliferation.',
    primaryBenefits: ['Muscle recovery', 'Injury healing', 'Flexibility', 'Anti-inflammatory'],
    sideEffects: ['Fatigue (temporary)', 'Nausea (rare)', 'Head rush'],
    dosing: {
      typical: '2–2.5 mg',
      range: '1–5 mg',
      frequency: 'Twice weekly (loading), then weekly (maintenance)',
      route: ['subcutaneous', 'intramuscular'],
      cycleLength: '4–6 weeks loading, ongoing maintenance',
      breakLength: '4–8 weeks',
    },
    goals: ['healing', 'joints-pain', 'muscle-gain'],
    stacks: { synergistic: [{ id: 'bpc-157', reason: 'Synergistic healing stack' }], redundant: [], complementary: [] },
    halfLife: 'Unknown',
    storage: 'Refrigerate after reconstitution; stable ~30 days.',
    reconstitution: 'Reconstitute with bacteriostatic water.',
    experienceLevel: 'intermediate',
  },
  {
    id: 'ipamorelin',
    name: 'Ipamorelin',
    aliases: ['IPA'],
    categories: ['gh-secretagogue'],
    description: 'A selective GH secretagogue that stimulates GH release without significantly raising cortisol or prolactin.',
    mechanism: 'Mimics ghrelin and binds to GHS-R receptors to stimulate pulsatile GH release.',
    primaryBenefits: ['Growth hormone release', 'Fat loss', 'Muscle gain', 'Improved sleep'],
    sideEffects: ['Water retention', 'Numbness/tingling', 'Increased hunger'],
    dosing: {
      typical: '200–300 mcg',
      range: '100–500 mcg',
      frequency: '2–3x daily',
      route: ['subcutaneous'],
      cycleLength: '8–16 weeks',
      breakLength: '4–8 weeks',
      timing: 'Pre-sleep and/or pre-workout on empty stomach',
    },
    goals: ['muscle-gain', 'weight-loss', 'sleep', 'anti-aging'],
    stacks: { synergistic: [{ id: 'cjc-1295', reason: 'Classic GH stack for amplified pulse' }], redundant: [], complementary: [] },
    halfLife: '~2 hours',
    storage: 'Refrigerate; stable 60–90 days after reconstitution.',
    reconstitution: 'Reconstitute with bacteriostatic water.',
    experienceLevel: 'beginner',
  },
  {
    id: 'cjc-1295',
    name: 'CJC-1295',
    aliases: ['CJC-1295 DAC', 'Mod GRF 1-29'],
    categories: ['gh-secretagogue'],
    description: 'A long-acting GHRH analogue that sustains elevated GH and IGF-1 levels.',
    mechanism: 'Binds and stimulates GHRH receptors on pituitary somatotrophs.',
    primaryBenefits: ['Sustained GH elevation', 'Muscle growth', 'Fat metabolism', 'Recovery'],
    sideEffects: ['Water retention', 'Fatigue', 'Flushing', 'Tingling'],
    dosing: {
      typical: '1–2 mg',
      frequency: 'Once weekly (DAC form)',
      route: ['subcutaneous'],
      cycleLength: '8–16 weeks',
      breakLength: '4–8 weeks',
    },
    goals: ['muscle-gain', 'weight-loss', 'anti-aging'],
    stacks: { synergistic: [{ id: 'ipamorelin', reason: 'Classic GH pulse amplifier' }], redundant: [], complementary: [] },
    halfLife: '5–8 days (DAC form)',
    storage: 'Refrigerate; stable 60–90 days after reconstitution.',
    reconstitution: 'Reconstitute with bacteriostatic water.',
    experienceLevel: 'intermediate',
  },
  {
    id: 'semaglutide',
    name: 'Semaglutide',
    aliases: ['GLP-1', 'Ozempic', 'Wegovy'],
    categories: ['weight-loss', 'metabolic'],
    description: 'A GLP-1 receptor agonist used for weight management and blood sugar control.',
    mechanism: 'Mimics GLP-1 to reduce appetite, slow gastric emptying, and improve insulin sensitivity.',
    primaryBenefits: ['Significant weight loss', 'Blood sugar regulation', 'Cardiovascular benefits', 'Reduced appetite'],
    sideEffects: ['Nausea', 'Vomiting', 'Diarrhea', 'Constipation', 'Pancreatitis risk'],
    dosing: {
      typical: '0.25–2.4 mg/week',
      range: '0.25–2.4 mg',
      frequency: 'Once weekly',
      route: ['subcutaneous'],
      cycleLength: 'Ongoing / as prescribed',
      timing: 'Same day each week',
    },
    goals: ['weight-loss', 'visceral-fat-loss'],
    stacks: { synergistic: [], redundant: [], complementary: [] },
    halfLife: '~7 days',
    storage: 'Refrigerate; protect from light.',
    experienceLevel: 'intermediate',
  },
  {
    id: 'ghk-cu',
    name: 'GHK-Cu',
    aliases: ['Copper Peptide'],
    categories: ['anti-aging', 'skin', 'healing'],
    description: 'A naturally occurring copper-binding peptide with potent regenerative and anti-aging effects.',
    mechanism: 'Activates wound healing, stimulates collagen synthesis, and modulates inflammatory response.',
    primaryBenefits: ['Skin rejuvenation', 'Collagen production', 'Hair growth', 'Anti-inflammatory'],
    sideEffects: ['Generally well tolerated', 'Mild skin irritation (topical)', 'Potential copper overload at high doses'],
    dosing: {
      typical: '1–2 mg',
      frequency: 'Daily or EOD',
      route: ['subcutaneous', 'topical'],
      cycleLength: '4–12 weeks',
      breakLength: '4 weeks',
    },
    goals: ['anti-aging', 'skin', 'hair', 'healing'],
    stacks: { synergistic: [], redundant: [], complementary: [] },
    halfLife: 'Short (minutes to hours)',
    storage: 'Store in cool, dark place; refrigerate after reconstitution.',
    reconstitution: 'Reconstitute with bacteriostatic water or saline.',
    experienceLevel: 'beginner',
  },
  {
    id: 'pt-141',
    name: 'PT-141',
    aliases: ['Bremelanotide', 'Vyleesi'],
    categories: ['sexual-health'],
    description: 'A melanocortin receptor agonist used to enhance sexual function in both men and women.',
    mechanism: 'Activates melanocortin receptors (MC1R, MC4R) in the CNS to increase sexual desire.',
    primaryBenefits: ['Increased libido', 'Enhanced sexual arousal', 'Erectile function support'],
    sideEffects: ['Nausea', 'Flushing', 'Headache', 'Transient hypertension'],
    dosing: {
      typical: '1–2 mg',
      range: '0.5–3 mg',
      frequency: 'As needed (45–90 min before activity)',
      route: ['subcutaneous', 'intranasal'],
      cycleLength: 'As needed',
      timing: '45–90 minutes before sexual activity',
    },
    goals: ['sexual'],
    stacks: { synergistic: [], redundant: [], complementary: [] },
    halfLife: '~2.7 hours',
    storage: 'Refrigerate after reconstitution.',
    reconstitution: 'Reconstitute with bacteriostatic water.',
    experienceLevel: 'intermediate',
  },
  {
    id: 'selank',
    name: 'Selank',
    aliases: [],
    categories: ['cognitive', 'nootropic', 'immune'],
    description: 'A synthetic analogue of tuftsin with anxiolytic and nootropic properties.',
    mechanism: 'Modulates GABA and serotonin systems; upregulates BDNF expression.',
    primaryBenefits: ['Anxiety reduction', 'Cognitive enhancement', 'Mood improvement', 'Immune modulation'],
    sideEffects: ['Mild sedation', 'Nasal irritation (intranasal)', 'Fatigue'],
    dosing: {
      typical: '250–500 mcg',
      frequency: '1–3x daily',
      route: ['subcutaneous', 'intranasal'],
      cycleLength: '2–4 weeks',
      breakLength: '2 weeks',
    },
    goals: ['mental', 'immune', 'sleep'],
    stacks: { synergistic: [], redundant: [], complementary: [] },
    halfLife: '~3 minutes (plasma)',
    storage: 'Refrigerate; use within 14–21 days after reconstitution.',
    reconstitution: 'Reconstitute with bacteriostatic water or saline.',
    experienceLevel: 'intermediate',
  },
  {
    id: 'sermorelin',
    name: 'Sermorelin',
    aliases: ['GHRH 1-29'],
    categories: ['gh-secretagogue', 'anti-aging'],
    description: 'A GHRH analogue that stimulates pulsatile GH release from the pituitary.',
    mechanism: 'Binds GHRH receptors on pituitary somatotrophs to trigger GH pulses.',
    primaryBenefits: ['GH stimulation', 'Anti-aging effects', 'Improved body composition', 'Enhanced sleep'],
    sideEffects: ['Injection site reactions', 'Flushing', 'Headache', 'Dizziness'],
    dosing: {
      typical: '200–500 mcg',
      frequency: 'Nightly (pre-sleep)',
      route: ['subcutaneous'],
      cycleLength: '3–6 months minimum',
      breakLength: '1–3 months',
      timing: 'Immediately before bed on empty stomach',
    },
    goals: ['anti-aging', 'sleep', 'muscle-gain', 'weight-loss'],
    stacks: { synergistic: [{ id: 'ipamorelin', reason: 'Synergistic GH release' }], redundant: [], complementary: [] },
    halfLife: '~11 minutes',
    storage: 'Refrigerate; stable ~30 days after reconstitution.',
    reconstitution: 'Reconstitute with bacteriostatic water.',
    experienceLevel: 'beginner',
  },
  {
    id: 'epithalon',
    name: 'Epithalon',
    aliases: ['Epitalon', 'Epithalamin'],
    categories: ['anti-aging', 'sleep'],
    description: 'A tetrapeptide studied for telomerase activation and longevity effects.',
    mechanism: 'Activates telomerase enzyme, potentially lengthening telomeres and promoting cellular longevity.',
    primaryBenefits: ['Telomere lengthening', 'Improved sleep quality', 'Anti-aging', 'Antioxidant effects'],
    sideEffects: ['Generally well tolerated', 'Mild fatigue', 'Transient flu-like symptoms'],
    dosing: {
      typical: '5–10 mg/day for 10–20 days',
      frequency: 'Daily (during cycle)',
      route: ['subcutaneous', 'intramuscular'],
      cycleLength: '10–20 days',
      breakLength: '4–6 months',
    },
    goals: ['anti-aging', 'longevity', 'sleep'],
    stacks: { synergistic: [], redundant: [], complementary: [] },
    halfLife: 'Very short',
    storage: 'Refrigerate; minimize freeze-thaw cycles.',
    reconstitution: 'Reconstitute with bacteriostatic water.',
    experienceLevel: 'advanced',
  },
];
